### ISSUE TITLE
i wanna cry

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [MemeHoovy/Kade-Engine-1.8#1]
![Screenshot 2022-09-02 9 32 50 PM](https://user-images.githubusercontent.com/92174516/188254267-4968dcb8-7379-46c8-a977-27748a4d0119.png)

**Comment by MemeHoovy** [comment]
> ![Screenshot 2022-09-02 9 32 50 PM](https://user-images.githubusercontent.com/92174516/188254267-4968dcb8-7379-46c8-a977-27748a4d0119.png)

L, also idk how to fix that

**Comment by MemeHoovy** [comment]
> ![Screenshot 2022-09-02 9 32 50 PM](https://user-images.githubusercontent.com/92174516/188254267-4968dcb8-7379-46c8-a977-27748a4d0119.png)

idk how to fix that unfortunately
